######################## default configuration ####################
baseURL = "/"
languageCode = "es-CL"
title = "Budapets alimento para gatos y perros"
theme = "Hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Perros"
  URL = "perros"
  weight = 1
  
  [[menu.main]]
  name = "Gatos"
  URL = "gatos"
  weight = 2

  #[[menu.main]]
  #name = "Datos"
  #URL = "blog"
  #weight = 2
  
  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3  
  
  [[menu.main]]
  name = "Contacto"
  URL = "contact"
  weight = 4
  
  ############# footer menu #############
  #[[menu.footer]]
  #URL = "productos"
  #weight = 1
  
  #[[menu.footer]]
  #name = "Datos"
  #URL = "blog"
  #weight = 2
  
  #[[menu.footer]]
  #name = "FAQ"
  #URL = "faq"
  #weight = 3
  
  [[menu.footer]]
  name = "TÃ©rminos y Condiciones"
  URL = "terms-conditions"
  weight = 1
  
  #[[menu.footer]]
  #name = "Contacto"
  #URL = "contact"
  #weight = 5


#################### default parameters ################################
[params]
logo = "images/buda-inicio-2.png"
home = "Home"
# Meta data
description = "Alimento para gatos y perros"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "+56 9 7430 0846"
email = "javfrancs@gmail.com"
location = "Santiago, Chile"
# copyright
copyright = "| Copyright &copy; 2020 [RocoxLab](https://rocoxlab.cl) Todos los derechos Reservados |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  #Servicio RaaS (Rating as a service), para los blogs, entre otros
  [params.rating]
  enable = false
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/pg/BudapetsChile"
  
  [[params.social]]
  #icon = "ti-twitter-alt"
  #link = "#"
  
  [[params.social]]
  #icon = "ti-youtube"
  #link = "#"
  
  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/budapetschile/"
  
  [[params.social]]
  #icon = "ti-pinterest"
  #link = "#"

  # Contact Form
  [params.contact]
  formAction = "https://formspree.io/javfrancs@gmail.com" # contact form works with formspree.io